# Array test related variables
ARRAY_TEST_OBJECT := test_array.o
TEST_OBJECTS += $(ARRAY_TEST_OBJECT)

# Array test target
$(ARRAY_TEST_OBJECT):
	$(C) $(DEBUG_CFLAGS) -c $(ARRAY_TEST_INCLUDE)/test_array.c $(TEST_INCLUDE_DIRS)