# heap test related variables
HEAP_TEST_OBJECT := test_heap.o
TEST_OBJECTS += $(HEAP_TEST_OBJECT)

# heap test target
$(HEAP_TEST_OBJECT):
	$(C) -c $(HEAP_TEST_INCLUDE)/test_heap.c $(TEST_INCLUDE_DIRS)