# List test related variables
LIST_TEST_OBJECT := test_list.o
TEST_OBJECTS += $(LIST_TEST_OBJECT)

# List test target
$(LIST_TEST_OBJECT):
	$(C) -c $(LIST_TEST_INCLUDE)/test_list.c $(TEST_INCLUDE_DIRS)