# Array related variables
ARRAY_DIR := array
ARRAY_INCLUDE := $(SRC_DIR)/$(ARRAY_DIR)
INCLUDE_DIRS += $(ARRAY_DIR)
LIB_SUB_MAKES += $(ARRAY_INCLUDE)/Makefile

# Include all extra Makefiles
include $(LIB_SUB_MAKES)